Update boa 0.3.7
Sadly neo-boa stops support for classes, so I had to rewrite all code without OOP.

Changes:
- tests replaced with new based on neo-boa api, instead of wrapping neo-python
- alias switched from class to array format and added getters and setters for all properties to simplify manipulation

WARNING: parent modules inherits all childs imports, even in case of absolute imports, may cause compilation error: ErrorOverflow...
That is reason why lot of modules misses imports, but project works.